%% Waktu Tempuh
%% Varisasi 1
time_var1a = max(waktu_var1a);
time_var1b = max(waktu_var1b);
time_var1c = max(waktu_var1c);
time_var1d = max(waktu_var1d);
%% Variasi 2
time_var2a = max(waktu_var2a);
time_var2b = max(waktu_var2b);
time_var2c = max(waktu_var2c);
time_var2d = max(waktu_var2d);
%% Variasi 3
time_var3a = max(waktu_var3a);
time_var3b = max(waktu_var3b);
time_var3c = max(waktu_var3c);
time_var3d = max(waktu_var3d);
%% Varisasi 7 % Paling Max
time_var7a = max(waktu_var7a);
time_var7b = max(waktu_var7b);
time_var7c = max(waktu_var7c);
time_var7d = max(waktu_var7d);
%% Variasi 8
time_var8a = max(waktu_var8a);
time_var8b = max(waktu_var8b);
time_var8c = max(waktu_var8c);
time_var8d = max(waktu_var8d);
%% Variasi 9
time_var9a = max(waktu_var9a);
time_var9b = max(waktu_var9b);
time_var9c = max(waktu_var9c);
time_var9d = max(waktu_var9d);